version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./cesta.db:/app/cesta.db
    environment:
      - FLASK_ENV=production
    restart: always